Aqar/Areas/Admin/Controllers/CategoryController.cs
using Aqar.DataAccess.Repository.IRepository;
using Aqar.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Aqar.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_unitOfWork.Category.GetAll());
        }

    
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Category category = _unitOfWork.Category.GetById(c => c.Id == id);

            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, Category category)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var category = _unitOfWork.Category.GetById(c => c.Id == id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            var obj = _unitOfWork.Category.GetById(c => c.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Category.Remove(obj);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Aqar/Areas/Admin/Controllers/RealStateController.cs
using Aqar.DataAccess.Repository.IRepository;
using Aqar.Models;
using Aqar.Models.ViewModels;
using Aqar.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace AqarWeb.Areas.Admin.Controllers
{
    public class RealStateController : Controller
    {
        private readonly IUnitOfWork _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RealStateController(IUnitOfWork db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View(_db.RealState.GetAll());
        }
        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            ViewData["CatID"] = _db.Category.GetAll().ToList();
            return View(new RealStateVM());
        }
        [Authorize]
        [HttpPost]
        public IActionResult Create(RealStateVM realStateVM)
        {
            if (ModelState.IsValid)
            {
                if (realStateVM.ImageFiles != null)
                {
                    realStateVM.Images = new List<RealStateImagesVM>();

                    foreach (var file in realStateVM.ImageFiles)
                    {
                        var img = new RealStateImagesVM()
                        {
                            ImageUrl = UploadImage(file)
                        };

                        realStateVM.Images.Add(img);
                    }
                }
                _db.RealState.AddNewRealState(realStateVM);
                _db.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(realStateVM);
        }

        private string UploadImage(IFormFile file)
        {
            string uniqueFileName = null;

            string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, SD.FileUploadFolder);

            uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(fileStream);
            }

            //file.CopyTo(new FileStream(filePath, FileMode.Create));

            return uniqueFileName;
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var editTarget = _db.RealState.GetById(c=>c.Id==id);
            if (editTarget == null)
            {
                return NotFound();
            }
            return View(editTarget);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int? id, RealState RealState)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _db.RealState.Update(RealState);
                _db.Save();
                return RedirectToAction("Index");
            }
            return View(RealState);
        }
    }
}

Aqar/Areas/Customer/Controllers/SearchController.cs
using Aqar.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace AqarWeb.Areas.Customer.Controllers
{
    public class SearchController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public SearchController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            ViewData["Cat"] = _unitOfWork.Category.GetAll().ToList();
            ViewData["Sat"] = _unitOfWork.RealState.GetAll().ToList();
            return View("search");
        }

        public IActionResult Search(int CategoryId, string State)
        {
            ViewData["Cat"] = _unitOfWork.Category.GetAll().ToList();
            ViewData["Sat"] = _unitOfWork.RealState.GetAll().ToList();
            var ers = _unitOfWork.RealState.SearchByID(CategoryId, State);
            if (ers.Any()) { return PartialView("_SearchResult", ers); } else return PartialView("_NotFound");

        }
    }
}

Aqar/Views/Shared/DetailsLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="icon" type="image/jpg" href="Images/logo.jpg">

</head>
<body>
               @RenderBody()

<!-- ///////////////////////////////////////////////////////////////////// -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

Aqar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Aqar</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:wght@100;400;700;900&family=Supermercado+One&display=swap" rel="stylesheet">

   <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="icon" type="image/jpg" href="Images/logo.jpg">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light opacity-75 bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Aqar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="RealState" asp-action="Index">Explore</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Search" asp-action="Index">Search</a>
                         </li>
                    </ul>
                    <partial name="_LoginPartialCustom" />
                </div>
            </div>
        </nav>
    </header>
    <div class="w-100 h-100">
        <video autoplay muted loop id="myVideo" class="opacity-75">
  <source src="~/Images/كأنك بداخلها.. شاهد أحدث تصوير جوي لتقدم الأعمال الإنشائية في العاصمة الإدارية الجديدة.mp4" type="video/mp4">
</video>
    <div class="container">

        <main role="main" class="pb-3">
          
            @RenderBody()
        </main>
    </div></div>
    <footer class="border-top footer text-muted bg-white opacity-75 text-center">
        <div class="container">
            &copy; 2022 - Aqar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Aqar/Views/Shared/_LoginPartialCustom.cshtml
@*@using Microsoft.AspNetCore.Identity*@

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" href="#">Hello @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <form id="logoutForm" method="post" class="form-inline" asp-area="Account" asp-controller="Account" asp-action="LogOff">
                <button type="submit" class="btn nav-link">Logout</button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item me-4">
            <a class="nav-link" asp-area="Account" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Account" asp-controller="Account" asp-action="Login">Login</a>
        </li>
    }
</ul>

Aqar/Views/Shared/_NotFound.cshtml
<h1 class="text-dark" style="text-align:center;">There is No Real states with such Critieria</h1>

Aqar/Views/Shared/_SearchResult.cshtml
@model IEnumerable<RealState>

<div class="container-fluid">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-6  text-center d-flex">
                <div class="card">
                    <img class="card-img-top" src="~/Images/5.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                        <p class="card-text">
                            <p>
                                <i class="location-icon fa fa-map-marker-alt"></i>
                                    @item.FullAdress
                            </p>
                    </div>
                    <ul class="list-group list-group-flush mt-auto">
                        <li class="list-group-item"><span class="integer">@item.Area</span> M²</li>
                        <li class="list-group-item">
                            <span class="integer">@item.Price</span>
                            <span>EGP</span>
                        </li>
                    </ul>

                    <a href="#" class="card-link"><div class="card-body">Details</div></a>
                </div>
            </div>
        }
    </div>
</div>